//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

export const GroupAttendanceDetailDateSelectionMode = {
    None: 0,

    DatePicker: 1,

    CurrentDate: 2,

    ScheduledDatePicker: 3,

    Specific: 4
} as const;

export const GroupAttendanceDetailDateSelectionModeDescription: Record<number, string> = {
    0: "None",

    1: "Date Picker",

    2: "Current Date",

    3: "Scheduled Date Picker",

    4: "Specific"
};

export type GroupAttendanceDetailDateSelectionMode = typeof GroupAttendanceDetailDateSelectionMode[keyof typeof GroupAttendanceDetailDateSelectionMode];
