//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupAttendanceDetailDateSelectionMode } from "@Obsidian/Enums/Blocks/Groups/GroupAttendanceDetail/groupAttendanceDetailDateSelectionMode";
import { GroupAttendanceDetailLocationSelectionMode } from "@Obsidian/Enums/Blocks/Groups/GroupAttendanceDetail/groupAttendanceDetailLocationSelectionMode";
import { GroupAttendanceDetailScheduleSelectionMode } from "@Obsidian/Enums/Blocks/Groups/GroupAttendanceDetail/groupAttendanceDetailScheduleSelectionMode";
import { Guid } from "@Obsidian/Types";
import { GroupAttendanceDetailAttendanceBag } from "@Obsidian/ViewModels/Blocks/Groups/GroupAttendanceDetail/groupAttendanceDetailAttendanceBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

export type GroupAttendanceDetailInitializationBox = {
    addGroupMemberPageUrl?: string | null;

    addPersonAs?: string | null;

    areAttendeesSortedByFirstName: boolean;

    attendanceOccurrenceDate?: string | null;

    attendanceOccurrenceDateSelectionMode: GroupAttendanceDetailDateSelectionMode;

    attendanceOccurrenceGuid?: Guid | null;

    attendanceOccurrenceTypes?: ListItemBag[] | null;

    attendanceOccurrenceTypesSectionLabel?: string | null;

    campusGuid?: Guid | null;

    campusName?: string | null;

    /**
     * Gets or sets the error message. A non-empty value indicates that
     * an error is preventing the block from being displayed.
     */
    errorMessage?: string | null;

    groupGuid?: Guid | null;

    groupMembersSectionLabel?: string | null;

    groupName?: string | null;

    isAttendanceOccurrenceTypesSectionShown: boolean;

    isCampusFilteringAllowed: boolean;

    isConfigError: boolean;

    isDidNotMeetChecked: boolean;

    isFutureOccurrenceDateSelectionRestricted: boolean;

    isGroupNotFoundError: boolean;

    isNewAttendanceDateAdditionRestricted: boolean;

    isNewAttendeeAdditionAllowed: boolean;

    isNoAttendanceOccurrencesError: boolean;

    isNotAuthorizedError: boolean;

    isNotesSectionHidden: boolean;

    locationGuid?: Guid | null;

    locationLabel?: string | null;

    locationSelectionMode: GroupAttendanceDetailLocationSelectionMode;

    /** Gets or sets the navigation urls. */
    navigationUrls?: Record<string, string> | null;

    notes?: string | null;

    notesSectionLabel?: string | null;

    roster?: GroupAttendanceDetailAttendanceBag[] | null;

    scheduleGuid?: Guid | null;

    scheduleLabel?: string | null;

    scheduleSelectionMode: GroupAttendanceDetailScheduleSelectionMode;

    /** Gets or sets the security grant token. */
    securityGrantToken?: string | null;

    selectedAttendanceOccurrenceTypeValue?: string | null;
};
