//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";

export type GroupAttendanceAttendeeBag = {
    /** Gets or sets a value indicating whether this Rock.ViewModels.Blocks.Groups.GroupAttendanceDetail.GroupAttendanceAttendeeBag is attended. */
    attended: boolean;

    /** Gets or sets the campus ids that a person's families belong to. */
    campusIds?: Guid[] | null;

    /** Gets or sets the full name. */
    fullName?: string | null;

    /** Gets or sets the last name. */
    lastName?: string | null;

    mergedTemplate?: string | null;

    /** Gets or sets the name of the nick. */
    nickName?: string | null;

    /** Gets or sets the person identifier. */
    personId: number;
};
